using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using CodeGauge.Core.Models;

namespace CodeGauge.Report;

public static class JsonReporter
{
    public static string Render(ScoreResult result)
    {
        var payload = new
        {
            repo_name = result.RepoName,
            primary_language = result.PrimaryLanguage,
            total_score = result.TotalScore,
            category_scores = new
            {
                tests = result.CategoryScores.Tests,
                code_quality = result.CategoryScores.CodeQuality,
                commit_hygiene = result.CategoryScores.CommitHygiene,
                documentation = result.CategoryScores.Documentation,
                dependencies = result.CategoryScores.Dependencies,
                error_handling = result.CategoryScores.ErrorHandling,
                lint_formatting = result.CategoryScores.LintFormatting,
            },
            feedback = result.Feedback.Select(f => new
            {
                metric = f.Metric,
                score = f.Score,
                issue = f.Issue,
                recommendation = f.Recommendation
            }).ToArray(),
            summary_badge = new
            {
                score = result.TotalScore,
                color = result.SummaryBadge.Color
            }
        };

        var options = new JsonSerializerOptions
        {
            WriteIndented = true,
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
        };
        return JsonSerializer.Serialize(payload, options);
    }
}

public static class MarkdownReporter
{
    public static string Render(ScoreResult result)
    {
        var sb = new StringBuilder();
        var color = result.SummaryBadge.Color;
        sb.AppendLine($"# CodeGauge Report");
        sb.AppendLine($"**Repository:** {result.RepoName}");
        sb.AppendLine($"**Primary Language:** {result.PrimaryLanguage}");
        sb.AppendLine($"**Total Score:** {result.TotalScore} ({color.ToUpperInvariant()})");
        sb.AppendLine();
        sb.AppendLine("## Category Scores");
        sb.AppendLine($"- Tests & Coverage: {result.CategoryScores.Tests}/{CodeGauge.Core.Models.Weights.TestsCoverage}");
        sb.AppendLine($"- Code Quality: {result.CategoryScores.CodeQuality}/{CodeGauge.Core.Models.Weights.CodeQuality}");
        sb.AppendLine($"- Commit Hygiene: {result.CategoryScores.CommitHygiene}/{CodeGauge.Core.Models.Weights.CommitHygiene}");
        sb.AppendLine($"- Documentation: {result.CategoryScores.Documentation}/{CodeGauge.Core.Models.Weights.Documentation}");
        sb.AppendLine($"- Dependencies: {result.CategoryScores.Dependencies}/{CodeGauge.Core.Models.Weights.Dependencies}");
        sb.AppendLine($"- Error Handling: {result.CategoryScores.ErrorHandling}/{CodeGauge.Core.Models.Weights.ErrorHandling}");
        sb.AppendLine($"- Lint & Formatting: {result.CategoryScores.LintFormatting}/{CodeGauge.Core.Models.Weights.LintFormatting}");
        sb.AppendLine();
        sb.AppendLine("## Itemized Feedback");
        foreach (var f in result.Feedback)
        {
            sb.AppendLine($"- [{f.Metric}] (-{Math.Max(0, 0)} pts): {f.Issue}\n  - Recommendation: {f.Recommendation}");
        }
        sb.AppendLine();
        sb.AppendLine("## Badge");
        sb.AppendLine($"- Score: {result.TotalScore}");
        sb.AppendLine($"- Color: {result.SummaryBadge.Color}");
        sb.AppendLine();
        sb.AppendLine("_Generated by CodeGauge on " + result.GeneratedAtUtc.ToString("u") + "_\n");
        return sb.ToString();
    }
}
